baseURL = 'https://ka1hung.github.io/'
languageCode = 'en-us'
title = 'DizzyLand'
theme = 'PaperMod'
paginate = 10

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

googleAnalytics="G-SL32FHR5BB"

# å•Ÿç”¨æœå°‹åŠŸèƒ½
[outputs]
home = ["HTML", "RSS", "JSON"]

# åˆ†é¡è¨­å®š
[taxonomies]
tag = "tags"
category = "categories"
series = "series"


[params]
defaultTheme = "auto"
ShowShareButtons = true
ShowReadingTime = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowRssButtonInSectionTermList = true
ShowToc = true

# æœå°‹åŠŸèƒ½è¨­å®š
[params.homeInfoParams]
Title = "æ­¡è¿ä¾†åˆ°æˆ‘çš„éƒ¨è½æ ¼ ğŸ‘‹"
Content = "é€™æ˜¯ä¸€å€‹ä½¿ç”¨ Hugo å’Œ PaperMod ä¸»é¡Œå»ºç«‹çš„éƒ¨è½æ ¼"

[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1000
threshold = 0.4
minMatchCharLength = 0
keys = ["title", "permalink", "summary", "content"]

# ç¤¾ç¾¤é€£çµ
[[params.socialIcons]]
name = "github"
url = "https://github.com/ka1hung"

# ä¸»é¸å–®è¨­å®š
[[menu.main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 10

[[menu.main]]
identifier = "categories"
name = "Catagories"
url = "/categories/"
weight = 20

[[menu.main]]
identifier = "tags"
name = "tags"
url = "/tags/"
weight = 30

[[menu.main]]
identifier = "series"
name = "seriers"
url = "/series/"
weight = 40

[[menu.main]]
identifier = "archives"
name = "archives"
url = "/archives/"
weight = 50



# [[params.socialIcons]]
# name = "twitter"
# url = "https://twitter.com/"

